version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vishnu
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sg-app
